<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class DocumentsProfileProxy extends \Documents\Profile implements \Doctrine\ODM\MongoDB\Proxy\Proxy
{
    public $__dm;
    public $__identifier;
    public $__isInitialized__ = false;

    public function __construct($dm, $identifier)
    {
        $this->__dm = $dm;
        $this->__identifier = $identifier;
        $this->__dm->getClassMetadata(__CLASS__)->setIdentifierValue($this, $this->__identifier);
    }

    private function _load()
    {
        if (!$this->__isInitialized__ && $this->__dm) {
            $this->__isInitialized__ = true;
            if ($this->__dm->loadByID(get_class($this), $this->__identifier, true) === null) {
                throw new \Doctrine\ODM\MongoDB\DocumentNotFoundException();
            }
            unset($this->__dm);
            unset($this->__identifier);
        }
    }

    
    public function getProfileId()
    {
        $this->_load();
        return parent::getProfileId();
    }

    public function setFirstName($firstName)
    {
        $this->_load();
        return parent::setFirstName($firstName);
    }

    public function getFirstName()
    {
        $this->_load();
        return parent::getFirstName();
    }

    public function setLastName($lastName)
    {
        $this->_load();
        return parent::setLastName($lastName);
    }

    public function getLastName()
    {
        $this->_load();
        return parent::getLastName();
    }

    public function setImage(\Documents\File $image)
    {
        $this->_load();
        return parent::setImage($image);
    }

    public function getImage()
    {
        $this->_load();
        return parent::getImage();
    }


    public function __sleep()
    {
        if (!$this->__isInitialized__) {
            throw new \RuntimeException("Not fully loaded proxy can not be serialized.");
        }
        return array('profileId', 'firstName', 'lastName', 'image');
    }
}