<?php

declare(strict_types=1);

namespace Documents;

use Doctrine\ODM\MongoDB\Repository\DocumentRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends DocumentRepository
{
}
