<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class DocumentsAccountProxy extends \Documents\Account implements \Doctrine\ODM\MongoDB\Proxy\Proxy
{
    public $__dm;
    public $__identifier;
    public $__isInitialized__ = false;

    public function __construct($dm, $identifier)
    {
        $this->__dm = $dm;
        $this->__identifier = $identifier;
        $this->__dm->getClassMetadata(__CLASS__)->setIdentifierValue($this, $this->__identifier);
    }

    private function _load()
    {
        if ( ! $this->__isInitialized__ && $this->__dm) {
            $this->__isInitialized__ = true;
            if ($this->__dm->loadByID(get_class($this), $this->__identifier, true) === null) {
                throw new \Doctrine\ODM\MongoDB\DocumentNotFoundException();
            }
            unset($this->__dm);
            unset($this->__identifier);
        }
    }

    
    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function setName($name)
    {
        $this->_load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->_load();
        return parent::getName();
    }

    public function __toString()
    {
        $this->_load();
        return parent::__toString();
    }


    public function __sleep()
    {
        if ( ! $this->__isInitialized__) {
            throw new \RuntimeException("Not fully loaded proxy can not be serialized.");
        }
        return array('id', 'name');
    }
}