<?php

namespace ;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * serRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class serRepository extends DocumentRepository
{
}