name: "Documentation"

on:
  pull_request:
    branches:
      - "*.x"
    paths:
      - .github/workflows/documentation.yml
      - docs/**
  push:
    branches:
      - "*.x"
    paths:
      - .github/workflows/documentation.yml
      - docs/**

jobs:
  documentation:
    name: "Generate documentation"
    uses: "doctrine/.github/.github/workflows/documentation.yml@v12.2.0"
